config/routes.rb
Communique::Engine.routes.draw do
  # custom routes first
  #match 'messages/trash' => 'messages#trash', :as => :trash
  #match 'messages/unread' => 'messages#unread', :as => :unread
  #match 'messages/drafts' => 'messages#drafts', :as => :drafts
  #match 'messages/drafts/:id/delete' => 'messages#destroy_draft', :as => :destroy_draft
  #match 'messages/drafts/:id/trash' => 'messages#trash_draft_message', :as => :trash_draft
  #match 'messages/sent' => 'messages#sent', :as => :sent
  #match 'messages/sent/:id' => 'messages#show_sent', :as => :show_sent
  #match 'messages/sent/:id/delete' => 'messages#destroy_sent', :as => :destroy_sent
  #match 'messages/sent/:id/trash' => 'messages#trash_sent_message', :as => :trash_sent
  #match 'messages/:id/reply' => 'messages#reply', :as => :reply
  #match 'messages/:id/delete' => 'messages#destroy', :as => :destroy
  #match 'messages/:id/trash' => 'messages#trash_message', :as => :trash
  #match 'messages/bulk/delete' => 'messages#bulk_destroy', :as => :bulk_destroy, :via => [:post]
  #match 'messages/bulk/trash' => 'messages#bulk_trash', :as => :bulk_trash, :via => [:post]

  delete_paths = Proc.new do
    member do
      post 'trash'
      post 'delete'
      post 'restore'
    end
    collection do
      post 'bulk_trash'
      post 'bulk_delete'
    end
  end
 
  match '/messages' => redirect('/messages/inbox')

  namespace :messages do
    resources :inbox, :only => [:index, :show] do
      get 'reply', on: :member
      delete_paths.call
    end
    resources :trash, :only => [:index, :show]
    resources :sent, :except => [:new, :create, :edit, :update] do
      delete_paths.call
    end
    resources :drafts, :except => [:show] do
      post 'send_draft', on: :member
      delete_paths.call
    end
  end 
end

app/models/communique/outgoing_message.rb
require_relative '../../shared/status_scopes'

module Communique
  class OutgoingMessage < ActiveRecord::Base
    before_save :trim_recipients

    include Communique::Concerns::Deletable
    include Communique::Concerns::Trashable
    include Communique::Concerns::Sendable

    extend Shared::StatusScopes

    attr_accessible :content, :deleted, :draft, :sender_id, :subject, :recipients

    validates_presence_of :sender_id, :recipients, :subject, :content

    default_scope where(deleted: false).order("created_at DESC")

    def initialize
      super
      write_attribute(:deleted, false)
      write_attribute(:trashed, false)
    end

    def self.for(sender)
      where(sender_id: sender.id)
    end

    private

    def trim_recipients
      self.recipients.gsub!(/\s+/, "")
    end
  end
end

app/controllers/communique/messages/outgoing_messages_controller.rb
module Communique
  module Messages
    class OutgoingMessagesController < ApplicationController

      def trash
        @message = author_message
        back_to_inbox and return unless @message
        @message.mark_as_trashed
        redirect_to(params[:redirect_path] || :back)
      end

      def delete
        @message = author_message
        back_to_inbox and return unless @message
        @message.mark_as_deleted
        redirect_to(params[:redirect_path] || :back)
      end

      def restore
        @message = author_message
        back_to_inbox and return unless @message
        @message.unmark_as_trashed
        redirect_to(params[:redirect_path] || :back)
      end

      private

      def author_message
        authored_by_user.find_by_id(params[:id])
      end

      def back_to_inbox
        redirect_to messages_inbox_index_path
      end
    end
  end
end

app/views/communique/outgoing_messages/partials/_inbox_links.html.slim
li = link_to I18n.t('messages.links.compose'), new_messages_draft_path
li = link_to I18n.t('messages.links.inbox') + "(#{@count})", messages_inbox_index_path
li = link_to I18n.t('messages.links.sent'), messages_sent_index_path
li = link_to I18n.t('messages.links.drafts'), messages_drafts_path
li = link_to I18n.t('messages.links.trash'), messages_trash_index_path

app/views/communique/outgoing_messages/partials/_recipient_based_headings.html.slim
thead
  tr
    th
      input id="select_all" type="checkbox"
    th.span2 = I18n.t('messages.headings.recipient')
    th.span5 = I18n.t('messages.headings.subject')
    th.span1 = I18n.t('messages.headings.date')
    th.span1 = I18n.t('messages.headings.actions')

app/views/communique/outgoing_messages/partials/_sender_based_headings.html.slim
thead
  tr
    th
      input id="select_all" type="checkbox"
    th.span2 = I18n.t('messages.headings.sender')
    th.span5 = I18n.t('messages.headings.subject')
    th.span1 = I18n.t('messages.headings.date')
    th.span1 = I18n.t('messages.headings.actions')

app/views/communique/outgoing_messages/partials/_wysihtml5_toolbar.html.slim
#wysihtml5-toolbar style="display: none;"
  a data-wysihtml5-command="bold" title="CTRL+B" bold
  |  | 
  a data-wysihtml5-command="italic" title="CTRL+I" italic
  |  | 
  a data-wysihtml5-command="createLink" link
  |  | 
  a data-wysihtml5-command="insertImage" image
  |  | 
  a data-wysihtml5-command="formatBlock" data-wysihtml5-command-value="h1" h1
  |  | 
  a data-wysihtml5-command="formatBlock" data-wysihtml5-command-value="h2" h2
  |  | 
  a data-wysihtml5-command="insertUnorderedList" ul
  |  | 
  a data-wysihtml5-command="insertOrderedList" ol
  |  | 
  a data-wysihtml5-command="undo" undo
  |  | 
  a data-wysihtml5-command="redo" redo
  |  | 
  div data-wysihtml5-dialog="insertImage" style="display: none;"
    label
      | Image:
      input data-wysihtml5-dialog-field="src" value="http://"
    label
      | Align:
      select data-wysihtml5-dialog-field="className"
        option value=""
        option value="wysiwyg-float-left"
        option value="wysiwyg-float-right"
      a data-wysihtml5-dialog-action="save"
    a data-wysihtml5-dialog-action="cancel" 